/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views.admin.internalframes;

import javax.swing.table.DefaultTableModel;
import controllers.DataNasabahController;
import controllers.JabatanController;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import models.NasabahModel;
import models.JabatanModel;
import enums.StatusNasabahEnum;


/**
 *
 * @author Aziz
 * @author wtf
 */

public class DataNasabahView extends javax.swing.JInternalFrame {
    private List<NasabahModel> nasabahList;
    
    /**
     * Creates new form DataNasabah
     */
    public DataNasabahView() {
        initComponents();
        loadDataNasabah();
        
        javax.swing.plaf.basic.BasicInternalFrameUI ui = 
        (javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI();
        if (ui.getNorthPane() != null) {
            ui.getNorthPane().removeMouseListener(ui.getNorthPane().getMouseListeners()[0]);
        }
    }

    private void loadDataNasabah() {
    DefaultTableModel model = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }  
    };
    
    model.addColumn("ID");
    model.addColumn("Jabatan");
    model.addColumn("Nama");
    model.addColumn("Username");
    model.addColumn("Status");
    
    nasabahList = DataNasabahController.getAllNasabah();
    
    for (NasabahModel nasabah : nasabahList) {
        Object[] rowData = new Object[5];
        
        rowData[0] = nasabah.getId();
        rowData[1] = nasabah.getJabatan();
        rowData[2] = nasabah.getNama();
        rowData[3] = nasabah.getUsername();
        rowData[4] = nasabah.getStatus();
        
        model.addRow(rowData);
    }
    
    jTable1.setModel(model);
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showEditFormInDialog(int selectedRow) {
        NasabahModel nasabah = nasabahList.get(selectedRow);
        
        JTextField tfNama = new JTextField(nasabah.getNama(), 20);
        JTextField tfUsername = new JTextField(nasabah.getUsername(), 20);
        JTextField tfPassword = new JTextField(20);
        
        JComboBox<StatusNasabahEnum> cbStatus = new JComboBox<>(StatusNasabahEnum.values());
        for (StatusNasabahEnum status : StatusNasabahEnum.values()) {
            if (status.getLabel().equalsIgnoreCase(nasabah.getStatus())) {
                cbStatus.setSelectedItem(status);
                break;
            }
        }

        JComboBox<JabatanModel> cbJabatan = new JComboBox<>();
        List<JabatanModel> jabatanList = JabatanController.getAllJabatan();
        for (JabatanModel jabatan : jabatanList) {
            cbJabatan.addItem(jabatan);
            if (jabatan.getNama().equalsIgnoreCase(nasabah.getJabatan())) {
                cbJabatan.setSelectedItem(jabatan);
            }
        }
        
        // Panel form layout
        JPanel formPanel = new JPanel();
        formPanel.setLayout(new BoxLayout(formPanel, BoxLayout.Y_AXIS));
        formPanel.add(new JLabel("Nama Lengkap:"));
        formPanel.add(tfNama);
        formPanel.add(Box.createVerticalStrut(10)); 
        formPanel.add(new JLabel("Username:"));
        formPanel.add(tfUsername);
        formPanel.add(Box.createVerticalStrut(10));
        formPanel.add(new JLabel("Password:"));
        formPanel.add(tfPassword);
        formPanel.add(Box.createVerticalStrut(10));
        formPanel.add(new JLabel("Jabatan:"));
        formPanel.add(cbJabatan);
        formPanel.add(Box.createVerticalStrut(10));
        formPanel.add(new JLabel("Status:"));
        formPanel.add(cbStatus);
        
        int result = JOptionPane.showConfirmDialog(this, formPanel, "Edit Data Nasabah",
          JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        
        if (result == JOptionPane.OK_OPTION) {
            nasabah.setNama(tfNama.getText());
            nasabah.setUsername(tfUsername.getText());
            nasabah.setPassword(tfPassword.getText());
            
            StatusNasabahEnum selectedStatus = (StatusNasabahEnum) cbStatus.getSelectedItem();
            nasabah.setStatus(selectedStatus);

            JabatanModel selectedJabatan = (JabatanModel) cbJabatan.getSelectedItem();
            nasabah.setJabatan(selectedJabatan.getNama());

            boolean success = DataNasabahController.updateNasabah(nasabah);
            if (success) {
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui.");
                loadDataNasabah();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui data.");
            }
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        
        if(selectedRow >= 0) {
            showEditFormInDialog(selectedRow);
        } else {
            JOptionPane.showMessageDialog(this, "Tidak ada baris yang dipilih!");
            return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
