/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views.admin.internalframes;

import javax.swing.table.DefaultTableModel;
import controllers.DataNasabahController;

/**
 *
 * @author Aziz
 */
public class DataNasabahView extends javax.swing.JInternalFrame {

    /**
     * Creates new form DataNasabah
     */
    public DataNasabahView() {
        initComponents();
        loadDataNasabah();
        
        javax.swing.plaf.basic.BasicInternalFrameUI ui = 
        (javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI();
        if (ui.getNorthPane() != null) {
            ui.getNorthPane().removeMouseListener(ui.getNorthPane().getMouseListeners()[0]);
        }
    }

    private void loadDataNasabah() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Jabatan");
    model.addColumn("Nama");
    model.addColumn("Username");
    model.addColumn("Status");
    
    String[][] dataNasabah = DataNasabahController.getAllNasabah();
    
    for (Object[] row : dataNasabah) {
        model.addRow(row);
    }
    
    jTable1.setModel(model);
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
