/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views.admin.internalframes;

import controllers.PinjamanController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import views.customComponents.TableActionCellEditor;
import views.customComponents.TableActionCellRender;
import views.customComponents.TableActionEvent;

/**
 *
 * @author wtf
 */
public class PinjamanView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PinjamanView
     */
    public PinjamanView() {
        initComponents();
        loadPinjaman();
        renderPanelAction();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nasabah", "Nominal", "Alasan", "Tenor", "Tanggal", "Status", "Aksi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(40);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadPinjaman() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nasabah");
        model.addColumn("Nominal");
        model.addColumn("Alasan");
        model.addColumn("Tenor (Bulan)");
        model.addColumn("Tanggal");
        model.addColumn("Status");
        model.addColumn("Aksi");
       
        List<String[]> pinjamanList = PinjamanController.getAllPinjaman();
        
        for (String[] row : pinjamanList) {
            Object[] rowData = new Object[8];
            rowData[0] = row[0];
            rowData[1] = row[1];
            rowData[2] = row[2];
            rowData[3] = row[3];
            rowData[4] = row[4];
            rowData[5] = row[5];
            rowData[6] = row[6];

            model.addRow(rowData);
        }
        
        jTable1.setModel(model);
    }
    
    private void renderPanelAction() {
        TableActionEvent ev = new TableActionEvent() {
            @Override
            public void onAccept(int row) {
                String idStr = jTable1.getValueAt(row, 0).toString();
                int IdPinjaman = Integer.parseInt(idStr);
                
                boolean success = PinjamanController.setujuiPinjaman(IdPinjaman);
                
                if(!success) {
                    JOptionPane.showMessageDialog(PinjamanView.this, "Gagal Mengubah Status!");
                }
                
                loadPinjaman();
                renderPanelAction();
            }

            @Override
            public void onRefuse(int row) {
                String idStr = jTable1.getValueAt(row, 0).toString();
                int IdPinjaman = Integer.parseInt(idStr);
                
                boolean success = PinjamanController.tolakPinjaman(IdPinjaman);
                
                if(!success) {
                    JOptionPane.showMessageDialog(PinjamanView.this, "Gagal Mengubah Status!");
                }
                
                loadPinjaman();
                renderPanelAction();
            }

            @Override
            public void onDetail(int row) {
                String id = jTable1.getValueAt(row, 0).toString();
                String nasabah = jTable1.getValueAt(row, 1).toString();
                String nominal = jTable1.getValueAt(row, 2).toString();
                String alasan = jTable1.getValueAt(row, 3).toString();
                String tenor = jTable1.getValueAt(row, 4).toString();
                String tanggal = jTable1.getValueAt(row, 5).toString();
                String status = jTable1.getValueAt(row, 6).toString();

                String detail = String.format(
                    "ID: %s\nNasabah: %s\nNominal: %s\nTenor: %s bulan\nTanggal: %s\nStatus: %s\n\nAlasan:\n%s",
                    id, nasabah, nominal, tenor, tanggal, status, alasan
                );

                JTextArea textArea = new JTextArea(detail);
                textArea.setWrapStyleWord(true);
                textArea.setLineWrap(true);
                textArea.setEditable(false);
                textArea.setCaretPosition(0);

                JScrollPane scrollPane = new JScrollPane(textArea);
                scrollPane.setPreferredSize(new java.awt.Dimension(400, 250)); 

                JOptionPane.showMessageDialog(
                    PinjamanView.this,
                    scrollPane,
                    "Detail Pinjaman",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }
        };
                
        jTable1.getColumnModel().getColumn(7).setCellRenderer(new TableActionCellRender());
        jTable1.getColumnModel().getColumn(7).setCellEditor(new TableActionCellEditor(ev));
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(80);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
